version: 2.1

orbs:
  golangci-lint: valimail/golangci-lint@volatile

jobs:
  unit-test:
    docker:
      - image: cimg/go:1.24.2
    steps:
      - checkout
      - run:
          name: "Running Unit Tests"
          command: "go test ./..."
  
  lint:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - golangci-lint/lint

workflows:
  run-tests: 
    jobs:
      - unit-test
      - lint