version: 2.1

jobs:
  unit-test:
    docker:
      - image: cimg/go:1.24.2
    steps:
      - checkout
      - run:
          name: "Running Unit Tests"
          command: "go test ./..."
  
  lint:
    docker:
      - image: golangci/golangci-lint:v2.1.1-alpine
    steps:
      - checkout
      - run: golangci-lint run

workflows:
  run-tests: 
    jobs:
      - unit-test
      - lint