version: 2.1

jobs:
  unit-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  run-tests: 
    jobs:
      - unit-test